apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  labels:
    app: ghost
spec:
  storageClassName: ghost-nfs-class
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/ghost/blog"
    server: 192.168.1.127
    readOnly: false