apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: ghost-mysql
spec:
  storageClassName: ghost-nfs-class
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/ghost/mysql"
    server: 192.168.1.127
    readOnly: false