kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: ghost
spec:
  storageClassName: ghost-nfs-class
  selector:
    matchLabels:
      app: ghost-mysql
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi