apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv
  labels:
    app: jira
spec:
  storageClassName: jira-nfs-class
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/jira/application"
    server: 172.29.1.73
    readOnly: false