kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: jira
spec:
  storageClassName: jira-nfs-class
  selector:
    matchLabels:
      app: jira-mysql
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi