apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: jira-mysql
spec:
  storageClassName: jira-nfs-class
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/jira/mysql"
    server: 172.29.1.73
    readOnly: false