apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-logs
  labels:
    app: gitlab
    volume: logs
spec:
  storageClassName: gitlab-nfs-class
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/gitlab/logs"
    server: 172.29.1.73
    readOnly: false