apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-pv-registry
  labels:
    app: docker
    volume: registry
spec:
  storageClassName: docker-nfs-class
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/share/kubernetesFiles/registry/registry"
    server: 172.29.1.73
    readOnly: false