apiVersion: v1
kind: Service
metadata:
  name: docker-service
  namespace: docker
  labels:
    app: docker
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 31300
  selector:
    app: docker
  type: NodePort
