apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
  namespace: docker
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      volumes:
      # - name: certs-vol
      #   persistentVolumeClaim:
      #     claimName: docker-pvc-certs
      - name: registry-vol
        persistentVolumeClaim:
          claimName: docker-pvc-registry

      containers:
        - image: registry:latest
          name: docker
          imagePullPolicy: IfNotPresent
          # env:
          # - name: REGISTRY_HTTP_TLS_CERTIFICATE
          #   value: "/certs/registry.crt"
          # - name: REGISTRY_HTTP_TLS_KEY
          #   value: "/certs/registry.key"
          ports:
            - containerPort: 5000
          volumeMounts:
          # - name: certs-vol
          #   mountPath: /certs
          - name: registry-vol
            mountPath: /var/lib/registry